version: 2

defaults: &defaults
  docker:
    - image: joatmon08/circleci-hashistack
  working_directory: /tmp/chrome-remote-desktop-pipeline
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: /home/circleci/key.json

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: set up credentials
          command: make credentials
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .terraformrc

  unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run some checks to ensure the infrastructure is ready to build
          command: make unit

  contract:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run some checks to ensure the workspace has correct variables
          command: INFRA_ENVIRONMENT=dev make contract

  plan:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Initialize
          command: INFRA_ENVIRONMENT=dev make init
      - run:
          name: Plan
          command: terraform plan

  apply:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:de:9c:90:74:4f:2d:2b:a8:aa:78:23:6a:99:a1:0b"
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Initialize
          command: INFRA_ENVIRONMENT=dev make init
      - run:
          name: Apply
          command: terraform apply -auto-approve
      - run:
          name: Set up Chrome remote desktop
          command: make remote-desktop

  destroy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Initialize
          command: INFRA_ENVIRONMENT=dev make init
      - run:
          name: Apply
          command: terraform destroy --force

workflows:
  version: 2
  image:
    jobs:
      - setup
      - unit:
          requires:
            - setup
          filters:
            branches:
              only: master
      - contract:
          requires:
            - unit
          filters:
            branches:
              only: master
      - plan:
          requires:
            - contract
          filters:
            branches:
              only: master
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: master
      - approve-destroy:
          type: approval
          requires:
            - apply
          filters:
            branches:
              only: master
      - destroy:
          requires:
            - approve-destroy
          filters:
            branches:
              only: master