version: 2

defaults: &defaults
  working_directory: /tmp/chrome-remote-desktop-pipeline
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: /home/circleci/key.json

jobs:

  setup:
    <<: *defaults
    docker:
      - image: joatmon08/circleci-hashistack
    steps:
      - checkout
      - run:
          name: set up credentials
          command: make credentials
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .terraformrc

  unit:
    <<: *defaults
    docker:
      - image: joatmon08/circleci-hashistack
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run some checks to ensure the infrastructure is ready to build
          command: make unit

  contract:
    <<: *defaults
    docker:
      - image: joatmon08/circleci-hashistack
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run some checks to ensure the workspace has correct variables
          command: make contract

  plan:
    <<: *defaults
    docker:
      - image: joatmon08/circleci-hashistack
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Initialize
          command: make init
      - run:
          name: Plan
          command: terraform plan

  apply:
    <<: *defaults
    docker:
      - image: joatmon08/circleci-hashistack
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  image:
    jobs:
      - setup
      - unit:
          requires:
            - setup
          filters:
            branches:
              only: master
      - contract:
          requires:
            - unit
          filters:
            branches:
              only: master
      - plan:
          requires:
            - contract
          filters:
            branches:
              only: master
      